[package]
name = "game_boy"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
regex = "1.7"
sdl2 = { version = "0.35", features = ["ttf", "image"] }
once_cell = "1.18"
chrono = "0.4"